config/routes.rb
Kinetic::Application.routes.draw do
  devise_for :users

  resources :rules, only: [:new, :create, :index, :edit, :show, :update, :destroy]
  resources :organizations, only: [:new, :create, :index, :edit, :update]
  resources :deals, only: [:new, :create, :index, :calculate, :schedule, :associate] do
    member do
      post :associate
      post :calculate
      post :schedule
    end
  end

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.is?(:admin) || current_user.is?(:moderator)
      @rules = current_organization.rules.includes(:deals)
      render(template: 'home/admin_home')
    elsif current_user.is?(:user)
      @commissions = current_user.commissions
      render(template: 'home/user_home')
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_my_commissions.html.haml
- if commissions.count > 0
  Commissions
  %table{class: "table table-striped table-bordered table-condensed"}
    %tr
      %th
        Payment Date
      %th
        Amount
    - commissions.each do |commission|
      %tr
        %td
          = format_date(commission.payment_date)
        %td
          = number_to_currency(commission.amount)
- else
  You have no commissions

app/views/home/_my_rules.html.haml
- if rules.count > 0
  Rules Report
  %table{class: "table table-striped table-bordered table-condensed"}
    %tr
      %th
        Name
      %th
        Deal Count
    - rules.each do |rule|
      %tr
        %td
          = rule.name
        %td
          = rule.deals.count
- else
  You have no rules

app/views/home/admin_home.html.haml
Welcome #{current_user.email} you are an administrator.
%ul
  %li
    = render 'my_rules', rules: @rules

app/views/home/index.html.haml
Welcome #{current_user.email}!
%ul
  - if current_user.is?(:admin)
    %li
      = link_to 'Commission rules', rules_path

  - if current_user.is?(:moderator)
    %li
      = link_to 'Deals', deals_path

app/views/home/user_home.html.haml
Welcome #{current_user.email} you are a broker.
%ul
  %li
    = render 'my_commissions', commissions: @commissions