config/routes.rb
Kinetic::Application.routes.draw do
  devise_for :users

  resources :rules, only: [:new, :create, :index, :edit, :show, :update, :destroy]
  resources :organizations, only: [:new, :create, :index, :edit, :update]
  resources :deals, only: [:new, :create, :index, :calculate, :schedule, :associate] do
    member do
      post :associate
      post :calculate
      post :schedule
    end
  end

  root to: 'home#index'
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization

  has_many :commissions

  has_many :commission_schedules
  has_many :rules, through: :commission_schedules

  validates :user,
    :organization,
    :name,
    :details,
    presence: true

  def get_decimal(key)
    get_detail(key) do |key_string|
      details[key_string].to_d
    end
  end

  def get_datetime(key)
    get_detail(key) do |key_string|
      DateTime.parse(details[key_string])
    end
  end

  def self.not_associated
    where('rules_associated_date IS NULL')
  end

  private

  def get_detail(key)
    key_string = key.to_s
    if details.key?(key_string)
      yield(key_string)
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter :is_moderator?

  def index
    @deals = Deal.all
    @scheduled_commissions = CommissionSchedule.all
    @commissions = Commission.all
  end

  def new
    @deal = Deal.new
    @users = User.all
  end

  def create
    @deal = Deal.new(deal_params)

    if @deal.save
      redirect_to action: :index
    else
      @users = User.all
      render :new
    end
  end

  def associate
    deal = Deal.find(params[:id])
    DealRulesAssociator.associate(deal.organization)
    redirect_to action: :index
  end

  def schedule
    deal = Deal.find(params[:id])
    deal.commission_schedules.each do |schedule|
      CommissionScheduler.schedule_payment_date(schedule)
      CommissionScheduler.schedule_calculation_date(schedule)
    end
    redirect_to action: :index
  end

  def calculate
    deal = Deal.find(params[:id])
    CommissionCalculator.calculate(deal)
    redirect_to action: :index
  end

  private

  def deal_params
    params.require(:deal).permit(
      :name,
      :organization_id,
      :user_id,
      :details
    )
  end
end

app/views/deals/index.html.haml
****** THIS PAGE IS FOR TESTING PURPOSES ONLY ******
%br
%br
Deals
%br
%table{class: "table table-striped table-bordered table-condensed"} 
  %tr
    %th
      Name
    %th
      Details
    %th
      User
    %th
      Organization
    %th
      Actions
  - @deals.each do |deal|
    %tr
      %td
        = deal.name
      %td
        = deal.details
      %td
        = deal.user.email
      %td
        = deal.organization.name
      %td
        = link_to 'Associate Rules', associate_deal_path(deal), method: 'POST'

= link_to 'New deal', new_deal_path
%br
%br
Commission Rules/Schedules
%br
%table{class: "table table-striped table-bordered table-condensed"}
  %tr
    %th
      Deal name
    %th
      Rule name
    %th
      Payment date
    %th
      Calculation date
    %th
      Actions
  - @scheduled_commissions.each do |schedule|
    %tr
      %td
        = schedule.deal.name
      %td
        = schedule.rule.name
      %td
        = format_date(schedule.commission_payment_date)
      %td
        = format_date(schedule.calculate_commission_date)
      %td
        = link_to 'Schedule', schedule_deal_path(schedule.deal), method: 'POST'
        = link_to 'Calculate', calculate_deal_path(schedule.deal), method: 'POST'
%br
%br
Commissions
%br
%table{class: "table table-striped table-bordered table-condensed"}
  %tr
    %th
      Deal name
    %th
      Rule name
    %th
      User email
    %th
      Payment date
    %th
      Payment amount
  - @commissions.each do |commission|
    %tr
      %td
        = commission.deal.name
      %td
        = commission.rule.name
      %td
        = commission.user.email
      %td
        = format_date(commission.payment_date)
      %td
        = number_to_currency(commission.amount)

app/views/deals/new.html.haml
****** THIS PAGE IS FOR TESTING PURPOSES ONLY ******
%br
= @deal.errors.full_messages
%br
= simple_form_for @deal do |form|
  = form.input :name
  = form.input :user_id
  = form.input :organization_id
  Enter details like this { "amount" => "100.00", "start_date" => "3/11/1980" }
  = form.input :details, as: :text
  = form.submit

Users:
%table{class: "table table-striped table-bordered table-condensed"}
  %tr
    %th
      User Id
    %th
      User Email
    %th
      Organization Id
    %th
      Organization Name
  - @users.each do |user|
    %tr
      %td
        #{user.id}
      %td
        #{user.email}
      %td
        #{user.organization.id}
      %td
        #{user.organization.name}