config/routes.rb
Kinetic::Application.routes.draw do
  devise_for :users

  resources :rules, only: [:new, :create, :index, :edit, :show, :update, :destroy]
  resources :organizations, only: [:new, :create, :index, :edit, :update]
  resources :deals, only: [:new, :create, :index, :calculate, :schedule, :associate] do
    member do
      post :associate
      post :calculate
      post :schedule
    end
  end

  root to: 'home#index'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users
  has_many :rules
  has_many :deals

  validates :name, presence: true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :is_moderator?

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])

    if @organization.update_attributes(organization_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/views/organizations/_form.html.haml
= simple_form_for organization do |form|
  = form.input :name
  = form.submit

app/views/organizations/edit.html.haml
= render 'form', organization: @organization

app/views/organizations/index.html.haml
Organizations
%table{class: "table table-striped table-bordered table-condensed"}
  %tr
    %th
      Name
    %th
      Actions
  - @organizations.each do |organization|
    %tr
      %td
        = organization.name
      %td
        = link_to 'Edit', edit_organization_path(organization)

= link_to 'New organization', new_organization_path

app/views/organizations/new.html.haml
= render 'form', organization: @organization