config/routes.rb
Kinetic::Application.routes.draw do
  devise_for :users

  resources :rules, only: [:new, :create, :index, :edit, :show, :update, :destroy]
  resources :organizations, only: [:new, :create, :index, :edit, :update]
  resources :deals, only: [:new, :create, :index, :calculate, :schedule, :associate] do
    member do
      post :associate
      post :calculate
      post :schedule
    end
  end

  root to: 'home#index'
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :applicability_engine, polymorphic: true
  belongs_to :calculation_date_engine, polymorphic: true
  belongs_to :compensation_engine, polymorphic: true
  belongs_to :payment_date_engine, polymorphic: true
  belongs_to :organization

  has_many :commission_schedules
  has_many :deals, through: :commission_schedules

  validates :name, presence: true
  validates :active, inclusion: { in: [true, false] }

  accepts_nested_attributes_for :applicability_engine,
    :calculation_date_engine,
    :compensation_engine,
    :payment_date_engine

  def self.deactivated
    where(active: false)
  end

  def self.live
    date_time_where = <<-SQL
start_date IS NULL AND end_date IS NULL OR
start_date <= ? AND end_date >= ? OR
start_date IS NULL AND end_date >= ? OR
start_date <= ? AND end_date is NULL
    SQL
    current_time = Time.now
    where(active: true).
      where(
        date_time_where,
        current_time,
        current_time,
        current_time,
        current_time
      )
  end

  def mutable?
    deals.count == 0
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_filter :is_admin?

  def index
    @rules = current_organization.rules
  end

  def new
    @rule = RuleBuilder.default_rule
  end

  def create
    @rule = RuleBuilder.create_from_params(rules_params, params[:rule])
    @rule.organization = current_organization
    if @rule.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
    @rule = Rule.find(params[:id])
  end

  def update
    @rule = RuleBuilder.update_from_params(
      Rule.find(params[:id]),
      rules_params,
      params[:rule]
    )

    if @rule.save
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    rule = Rule.find(params[:id])
    rule.destroy
    redirect_to action: :index
  end

  private

  def rules_params
    params.require(:rule).permit(
      :name,
      :start_date,
      :end_date,
      :active
    )
  end
end

app/views/rules/_form.html.haml
= simple_form_for rule do |form|
  = form.input :name
  = form.input :active, inline_label: 'Check to make this rule active'
  = form.input :start_date, as: :date_field, disabled: disabled
  = form.input :end_date, as: :date_field, disabled: disabled
  = form.simple_fields_for :calculation_date_engine do |calculation_date_form|
    %label
      Trigger to calculate
    = render 'rules/engines/date_offset_calculation_date', calculation_date_form: calculation_date_form, disabled: disabled
  = form.simple_fields_for :payment_date_engine do |payment_date_form|
    %label
      Trigger to pay
    = render 'rules/engines/date_offset_payment_date', payment_date_form: payment_date_form, disabled: disabled
  = form.simple_fields_for :applicability_engine do |applicability_form|
    = render 'rules/engines/basic_applicability', applicability_form: applicability_form, disabled: disabled
  = form.simple_fields_for :compensation_engine do |compensation_form|
    = render 'rules/engines/basic_compensation', compensation_form: compensation_form, disabled: disabled
  = form.button :submit

app/views/rules/edit.html.haml
- if !@rule.mutable?
  This rule is already associated with deals and cannot be modified.
= render 'form', rule: @rule, disabled: !@rule.mutable?

app/views/rules/index.html.haml
Commissions Rules
%table{class: "table table-striped table-bordered table-condensed"}
  %tr
    %th
      Name
    %th
      Status
    %th
      Start Date
    %th
      End Date
    %th
      Actions
  - @rules.each do |rule|
    %tr
      %td
        = rule.name
      %td
        = rule.active
      %td
        = format_date(rule.start_date)
      %td
        = format_date(rule.end_date)
      %td
        = link_to 'Edit', edit_rule_path(rule)
        - if rule.active?
          = link_to 'Deactivate', rule_path(rule), method: 'DELETE'

= link_to 'New rule', new_rule_path

app/views/rules/new.html.haml
= render 'form', rule: @rule, disabled: false